# fly.toml app configuration file generated for servant on 2023-06-27T02:44:08-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "servant"
primary_region = "gru"

[env]
  FIBO_BOT_ID = "735147814878969968"
  DISCORD_GUILD_ID = "1090364250335228104"
  WELCOME_CHANNEL_ID = "1090365408667766915"
  NEWS_CHANNEL_ID = "1090366456094543903"
  RULES_CHANNEL_ID = "1090365945559662735"
  INTRO_CHANNEL_ID = "1091144092014096414"

[[mounts]]
  source = "data"
  destination = "/data"

# [http_service]
#   internal_port = 3000
#   force_https = true
#   auto_stop_machines = true
#   auto_start_machines = true
#   min_machines_running = 0
#   processes = ["app"]
